### ISSUE TITLE
Some questions.

### ISSUE THREAD

**Issue by horizon86** [jonagamerpro1234/CustomJoinAndQuitMessages#23]
![image](https://user-images.githubusercontent.com/49552732/219849308-68a881b4-fb02-4113-80f3-f4f57a0b643d.png)

I had set `Hooks.LuckPerms.Enabled: false`, but it says that: `Cjm Softdepend: Luckperms false - Hook Enabled in config`, what is `Hook Enabled`?

https://github.com/jonagamerpro1234/CustomJoinAndQuitMessages/blob/033b062d7d16226083434d544504c872ef0fa129/CustomJoinAndQuitMessagesOld/src/main/java/jss/customjoinandquitmessages/hook/LuckPermsHook.java#L25-L37

This mean that when I installed Luckperms and set `Hooks.LuckPerms.Enabled: false`, it will log: `Luckperms false - Hook Enabled in config`, I'm a little confused. I didn't enable hooks, why it is not : `Luckperms false - Hook not Enabled in config` ?

**Comment by jonagamerpro1234** [comment]
Sorry, the message is incorrect as this message indicates that the features that work with LuckPerms are disabled, thanks for reporting this bug, I'll have it fixed for the next version
