### ISSUE TITLE
Unable to add links that don't end in .com?

### ISSUE THREAD

**Issue by ParkerVAlf** [jonagamerpro1234/CustomJoinAndQuitMessages#5]
Hello, the plugin works wonderfully but I'm attempting to add a link to my servers dynmap site upon joining. This link just consists of ServerIP:DynmapPort, so "12.123.12.123:4444" for example. Attempting to add this link does not allow it to be clickable.

**Comment by jonagamerpro1234** [comment]
It doesn't work, but you can try adding "https://" or "http://" and it might work.

example: "https://12.123.12.123:4444"

If you don't follow the problem, feel free to ask
